### ISSUE TITLE
What is being patched?

### ISSUE THREAD

**Issue by kruug** [dongle-the-gadget/W11ISOPatcher#2]
Since you start with a Windows 11 iso, what are you adding to the final Windows 11 iso?

**Comment by dongle-the-gadget** [comment]
1. It will replace appraiserres.dll with a Windows 10 version
2. It will mount the boot.wim (Bootable media) and add 3 registry keys.
```
[HKEY_LOCAL_MACHINE\Setup\LabConfig]
"BypassTPMCheck"=dword:00000001
"BypassSecureBootCheck"=dword:00000001
"BypassRAMCheck"=dword:00000001
```
